name: pages
dependencies:
  polymer: '^1.0.0-rc.18'
  polymer_elements: '^1.0.0-rc.9'
  web_socket_channel: '^1.0.4'
  rethinkdb_driver: '^2.3.1'
  ex_map:
    version: '^0.10.3'
    git: https://github.com/Rasarts/ExMap.git
  socket_system: 
    version: '^0.9.0'
    git: 'https://github.com/WhisperEngine/SocketSystem.git'
dev_dependencies:
  test: '^0.12.15+11'
transformers:
  - test/pub_serve:
      $include: test/**_test{.*,}.dart
